name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node 
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: pip install

      - name: Tests
        run: pytest
